import Layout from '@/components/layout/layout'
import './globals.css'

export const metadata = {
  title: 'yoonhu blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
