import Layout from '@/components/layout/layout'
import './globals.css'
import RootStyleRegistry from '../../lib/RootStyleRegistry'
import StyledComponentsRegistry from '../../lib/registry'

export const metadata = {
  title: 'yoonhu blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Layout>{children}</Layout>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
